### ISSUE TITLE
Value of type 'BFTask<AnyObject>' has no member 'continueOnSuccessWith'

### ISSUE THREAD

**Issue by sjmerel** [BoltsFramework/Bolts-Swift#70] opened 2018-02-20 20:15 UTC
I have a Swift iOS project that is using the Parse SDK, and was hoping to take advantage of the simplified syntax of the Bolts-Swift project.

Here was my code:
```
PFCloud.callFunction(inBackground:"patient_getMovements", withParameters:nil).continue(successBlock:
{
   task -> Any? in
   // ...
}
```

I added the Bolts-Swift dependency and import statement, and figured I could now do this, as shown in the docs:

```
PFCloud.callFunction(inBackground:"patient_getMovements", withParameters:nil).continueOnSuccessWith
{
   task -> Any? in
   // ...
}
```

But I get the error:
Value of type 'BFTask<AnyObject>' has no member 'continueOnSuccessWith'

What am I doing wrong? I'm confused as to what the relationship is between this and the Obj-C Bolts project (which seems to be what my project is still using).

**Comment by nlutsenko** [comment] 2019-01-04 06:56
Unfortunately, this is quite out of scope for Bolts-Swift.
The issue is better suited for the Parse SDK, frankly, since it's the API on that side that needs to support Swift-native API.

**Closed as completed by nlutsenko** 2019-01-04 06:56 UTC
